version: '3'

services:
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks: 
      - shopping_app

  redis:
    image: redis
    restart: always
    networks: 
      - shopping_app
       
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./server/public/images:/usr/src/app/public/images
    depends_on:
      - db
      - redis
    networks: 
      - shopping_app
  
  web:
    image: robbyawaldi/ecommerce_web:1.0.0
    restart: always
    depends_on:
      - server
    networks: 
      - shopping_app

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    environment: 
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - server
      # - web
      - db
      - redis
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}
    networks: 
      - shopping_app

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"



networks: 
  shopping_app:
    driver: bridge

volumes: 
  pgdata: