version: '3'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks: 
      - shopping_app

  redis:
    image: redis
    networks: 
      - shopping_app
       
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server/public/images:/usr/src/app/public/images
    depends_on:
      - db
      - redis
    networks: 
      - shopping_app
  
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - server
    networks: 
      - shopping_app

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/templates
    environment: 
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - server
      - web
      - db
      - redis
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}
    networks: 
      - shopping_app

networks: 
  shopping_app:
    driver: bridge

volumes: 
  pgdata: