version: '3'

services:
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks: 
      - shopping_app

  redis:
    image: redis
    restart: always
    networks: 
      - shopping_app
       
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./server/public/images:/usr/src/app/public/images
    depends_on:
      - db
      - redis
    networks: 
      - shopping_app
  
  web:
    image: robbyawaldi/ecommerce_web:1.0.0
    restart: always
    depends_on:
      - server
    networks: 
      - shopping_app

  nginx:
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./public_html:/public_html
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    environment: 
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - server
      - web
      - db
      - redis
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}
      - 443:443
    networks: 
      - shopping_app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email robbyawaldi@gmail.com --agree-tos --no-eff-email --force-renewal -d store.robbyawaldi.com
    networks: 
      - shopping_app

networks: 
  shopping_app:
    driver: bridge

volumes: 
  pgdata: